# Drives configuration for agent homeostatic system
drives:
  energy:
    setpoint: 0.7
    weight: 1.0
    initial: 0.65
    min: 0.0
    max: 1.0
    decay_rate: 0.01
  temperature:
    setpoint: 0.5
    weight: 0.8
    initial: 0.55
    min: 0.0
    max: 1.0
  social_proximity:
    setpoint: 0.3
    weight: 0.5
    initial: 0.25
    min: 0.0
    max: 1.0